CREATE TABLE IF NOT EXISTS `post_messages` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `sender_identifier` VARCHAR(60) DEFAULT NULL,
  `sender_name` VARCHAR(255) NOT NULL,
  `receiver_identifier` VARCHAR(60) NOT NULL,
  `message` TEXT NOT NULL,
  `express` BOOLEAN NOT NULL DEFAULT FALSE,
  `station` VARCHAR(255) DEFAULT NULL,
  `timestamp` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `is_read` BOOLEAN NOT NULL DEFAULT FALSE,
  PRIMARY KEY (`id`)
);
